#!/bin/sh

# the below command means:
# opt -print-callgraph is the function call to print the graph
# $1 is the first command line argument when someone calls pipair
# > $1.callgraph means output that function call to the file $1.callgraph
clang -emit-llvm -c $1 -o bitcode
opt -print-callgraph bitcode 1> $1.callgraph.bc 2> $1.callgraph.readme
java -cp .. Pi $@ 2> /dev/null